name: Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC (09:00 KST)
  workflow_dispatch: # 수동 실행용

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 통계 카드 SVG 생성·커밋
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: seonwooj0810
          BRANCH_NAME: main
          UTC_OFFSET: 9
